import type { SimulationSnapshot } from "./types";

export const sampleSnapshot: SimulationSnapshot = {
  algorithm: "Cost-Based Collective Control",
  status: "Running",
  speed: 1,
  traffic: "Normal",
  hallCalls: [
    { floor: 9, direction: "down", assigned: "B" },
    { floor: 6, direction: "up", assigned: "A" },
    { floor: 3, direction: "up", assigned: "C" },
  ],
  elevators: [
    {
      id: "A",
      status: "moving-up",
      floor: 4.7,
      fromFloor: 4,
      toFloor: 5,
      nextStop: 6,
      stops: [6, 8, 10],
      occupancy: 1,
      occupancyMax: 8,
      utilization: 68,
    },
    {
      id: "B",
      status: "doors-open",
      floor: 3,
      fromFloor: 3,
      toFloor: 3,
      nextStop: 9,
      stops: [9, 2],
      occupancy: 2,
      occupancyMax: 8,
      utilization: 54,
    },
    {
      id: "C",
      status: "moving-down",
      floor: 6.8,
      fromFloor: 7,
      toFloor: 6,
      nextStop: 3,
      stops: [3, 1],
      occupancy: 1,
      occupancyMax: 8,
      utilization: 72,
    },
  ],
  requests: [
    { id: "018", floor: 9, direction: "down", waitSeconds: 14.2, assigned: "B" },
    { id: "019", floor: 6, direction: "up", waitSeconds: 6.1, assigned: "A", highlighted: true },
    { id: "020", floor: 3, direction: "up", waitSeconds: 3.4, assigned: "C" },
  ],
  evaluation: {
    requestId: "018",
    selected: "A",
    rows: [
      { factor: "Distance (floors)", A: 1.2, B: 6.0, C: 5.8 },
      { factor: "Direction compatibility", A: 0.0, B: 2.5, C: 2.5 },
      { factor: "Scheduled stops", A: 1.5, B: 1.2, C: 1.4 },
      { factor: "Reverse penalty", A: 0.0, B: 1.0, C: 1.0 },
      { factor: "Waiting-age credit", A: 0.0, B: 0.0, C: 0.0 },
      { factor: "Total", A: 2.7, B: 10.7, C: 10.7, emphasize: true },
    ],
  },
  metrics: {
    averageWait: 7.4,
    longestWait: 21.8,
    averageJourney: 18.1,
    completedTrips: 42,
  },
  events: [
    { time: "10:14:03.281", type: "REQUEST", text: "F8 \u2193\uFE0E created" },
    { time: "10:14:03.284", type: "DISPATCH", text: "Request #018 \u2192\uFE0E Elevator C" },
    { time: "10:14:07.104", type: "ELEVATOR", elevatorId: "A", text: "Doors opened at F6" },
    { time: "10:14:09.622", type: "PASSENGER", text: "P041 boarded A, destination F9" },
    { time: "10:14:11.210", type: "REQUEST", text: "F6 \u2191\uFE0E created" },
    { time: "10:14:11.418", type: "DISPATCH", text: "Request #019 \u2192\uFE0E Elevator A" },
  ],
};
